### ISSUE TITLE
【Windows版本】登录+注册+忘记密码页面的一些问题

### ISSUE THREAD

**Issue by speauty** [langwan/chiyun#15]
当前环境：Windows 10 专业版 21H2 19044.2965
软件版本：痴云 Setup 0.9.17

1. 表单错误提示不及时响应，即输入手机号或密码后，下面的提示不消失（复现：进入登录界面，点击登录，然后输入手机密码），个人建议：手机号密码未输入，禁止点击登录，直接置灰，相对暴力；
2. 密码输入框无查看明码的小眼睛，建议后面空了还是补上；
3. 手机号缺少必要的验证，比如不够11位，也能提交请求，建议后期还是补上吧，能减少一定的不必要请求；
4. 注册页面，密码无必需验证？估计可能是漏了；

**Comment by speauty** [comment]
【不确定】直接点击登录，没有输入任何信息，会出现xhr请求，按理说，应该是表单验证的吧？
![image](https://github.com/langwan/chiyun/assets/28774023/d198248e-4cd5-4dbe-af0c-126131804f5d)

**Comment by speauty** [comment]
【体验性】登录 注册 忘记密码之间相互切换，是向中间收拢或展开的，不知道可不可以固定顶部，向下展开，虽然人眼焦点可能在中心位置，不过，页面不大，可能会产生一点错觉什么之类的。。。

另外，页面的标题（也就是注册，登录，忘记密码），距离首行输入框不一致，注册和登录看起来似乎是一样，没具体测量，不过忘记密码差距倒是相对比较明显。

**Comment by speauty** [comment]
【体验性】验证码模板似乎，完美迷册，与当前应用，关系不太明显，如果有时间，要不还是专门申请个短信模板

**Comment by langwan** [comment]
痴云的通道不让开，需要域名备案后，所以暂时是完美密册
